### ISSUE TITLE
Support for media

### ISSUE THREAD

**Issue by enkelmedia** [enkelmedia/Umbraco-MultiMover#2]
Version 0.1 does not support media but the moving process is very simular.

**Comment by pedroadaodev** [comment]
This would be GREAT!!! =)

**Comment by enkelmedia** [comment]
In Umbraco 8 there is nice support for this with the list view. I'll go ahead and close this one.

![image](https://user-images.githubusercontent.com/1782524/117218933-79b5ec80-ae04-11eb-832d-6273f7193ca2.png)
